apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-version-ci-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: clone-and-version
        template: clone-and-version
    - - name: build-and-push
        template: kaniko-build-git

  - name: clone-and-version
    container:
      image: node:18-alpine
      workingDir: /workspace
      command: [sh, -c]
      args:
        - |
          echo " GIT-BASED VERSIONING"
          apk add --no-cache git
          git clone https://github.com/vasplustechnologies/patient-appointment-api-v2.git /workspace
          cd /workspace
          
          # Get commit count for version
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VERSION="v$COMMIT_COUNT"
          echo " Version: $VERSION (based on $COMMIT_COUNT commits)"
          echo $VERSION > /tmp/version.txt
          
          npm install
          npx jest --passWithNoTests || echo "Tests completed"

  - name: kaniko-build-git
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [sh, -c]
      args:
        - |
          VERSION=$(cat /tmp/version.txt)
          echo " Building: $VERSION"
          
          /kaniko/executor \
            --context=git://github.com/vasplustechnologies/patient-appointment-api-v2.git \
            --destination=mofwili/patient-appointment-api:latest \
            --destination=mofwili/patient-appointment-api:$VERSION \
            --cache=true \
            --verbosity=info
          
          echo " Pushed: latest and $VERSION"
      env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-credentials
        items:
        - key: .dockerconfigjson
          path: config.json
