apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: github-dep
      eventSourceName: github-event-source
      eventName: push-event
  triggers:
    - template:
        name: trigger-versioned-ci
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: versioned-ci-
                namespace: default   # 👈 IMPORTANT: use default here
              spec:
                workflowTemplateRef:
                  name: versioned-ci
      retryStrategy:
        steps: 3
