apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: patient-api-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-dep
      eventSourceName: github-webhook
      eventName: patient-api-repo
  triggers:
    - template:
        name: trigger-basic-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-triggered-
                namespace: default
              spec:
                entrypoint: main
                templates:
                - name: main
                  container:
                    image: alpine:latest
                    command: [sh, -c]
                    args:
                    - |
                      echo " GitHub push detected!"
                      echo " Repository: {{ dependencies.github-dep.event.repository.full_name }}"
                      echo " Commit: {{ dependencies.github-dep.event.head_commit.id }}"
                      echo " Author: {{ dependencies.github-dep.event.head_commit.author.name }}"
                      echo " Trigger received successfully!"
